import type { Restaurant } from "./types";

// Verified Unsplash photo ids (all confirmed to load).
const P = {
  burger: "1568901346375-23c9450c58cd",
  burger2: "1571091718767-18b5b1457add",
  fries: "1573080496219-bb080dd4f877",
  chickenSandwich: "1626645738196-c2a7c87a8f58",
  shake: "1572490122747-3968b75cc699",
  ramen: "1569718212165-3a8278d5f624",
  ramen2: "1557872943-16a5ac26437e",
  tonkotsu: "1591814468924-caf88d1232e1",
  gyoza: "1496116218417-1a781b1c416c",
  matcha: "1515823064-d6e0c04616a7",
  sushi: "1579871494447-9811cf80d66c",
  nigiri: "1583623025817-d180a2221d0a",
  salmon: "1607301406259-dfb186e15de8",
  dragonroll: "1617196034796-73dfa7b1fd56",
  sake: "1514362545857-3bc16c4c7d1b",
  sparkling: "1536935338788-846bb9981813",
  pizza: "1513104890138-7c749659a591",
  pepperoni: "1628840042765-356cda07504e",
  margherita: "1574071318508-1cdbab80d002",
  mushroomPizza: "1604382354936-07c5d9983bd3",
  garlicBread: "1573140247632-f8fd74997d5c",
  tiramisu: "1571877227200-a0d98ea607e9",
  tacos1: "1565299585323-38d6b0865b47",
  tacos2: "1551504734-5ee1c4a1479b",
  burrito: "1626700051175-6818013e1d4f",
  nachos: "1582169296194-e4d644c48063",
  guac: "1600271886742-f049cd451bba",
  quesadilla: "1618040996337-56904b7850b9",
  salad: "1512621776951-a57141f2eefd",
  poke: "1546069901-ba9599a7e63c",
  avoToast: "1588137378633-dea1336ce1e2",
  smoothie: "1505252585461-04db1eb84625",
  grainBowl: "1467003909585-2f8a72700288",
  donut: "1551024506-0bccd828d307",
  cake: "1578985545062-69928b1d9587",
  cheesecake: "1533134242443-d4fd215305ad",
  croissant: "1555507036-ab1f4038808a",
  cookie: "1499636136210-6f4ee915583e",
  icecream: "1576506295286-5cda18df43e7",
  cappuccino: "1572442388796-11668a67e53d",
  espresso: "1510591509098-f4fdc6d0ff04",
  coldbrew: "1461023058943-07fcbe16d735",
  butterChicken: "1588166524941-3bf61a9c41db",
  tikka: "1565557623262-b51c2513a641",
  naan: "1601050690597-df0568f70950",
  biryani: "1563379091339-03b21ab4a4f8",
  pho: "1582878826629-29b7ad1cdc43",
  banhmi: "1600688640154-9619e002df30",
  springrolls: "1544025162-d76694265947",
  koreanChicken: "1575932444877-5106bee2a599",
  wings: "1608039755401-742074f0548d",
  pancakes: "1567620905732-2d1ec7ab7445",
  waffle: "1562376552-0d160a2f238d",
  padthai: "1559314809-0d155014e29e",
  greenCurry: "1455619452474-d2be8b1e70cd",
  thaiBasil: "1562565652-a0d8f0c59eb4",
  dumplings: "1563245372-f21724e3856d",
  friedRice: "1603133872878-684f208fb84b",
  chowMein: "1585032226651-759b368d7246",
  wonton: "1547928576-b822bc410bdf",
  falafel: "1593001874117-c99c800e3eb8",
  shawarma: "1529006557810-274b9b2fc783",
  hummus: "1633896949673-1eb9d131a9b4",
  greekSalad: "1540420773420-3366772f4999",
  brisket: "1529193591184-b1d58069ecdd",
  ribs: "1593030103066-0093718efeb9",
  pulledPork: "1513185158878-8d8c2a2a3da3",
  fishChips: "1580217593608-61931cefc821",
  shrimp: "1565680018434-b513d5e5fd47",
  calamari: "1599487488170-d11ec9c172f0",
  friedShrimp: "1626082896492-766af4eb6501",
  seafoodPlatter: "1559737558-2f5a35f4523b",
  bubbleTea: "1558857563-b371033873b8",
  milkTea: "1558160074-4d7d8bdf4256",
  eggsBenedict: "1608039829572-78524f79c4c7",
  steak: "1546833999-b9f581a1996d",
};

export const CATEGORIES = [
  { key: "all", label: "All", emoji: "All" },
  { key: "burger", label: "Burgers", emoji: "Bg" },
  { key: "chicken", label: "Chicken", emoji: "Ch" },
  { key: "noodle", label: "Noodles", emoji: "Nd" },
  { key: "sushi", label: "Sushi", emoji: "Su" },
  { key: "pizza", label: "Pizza", emoji: "Pz" },
  { key: "taco", label: "Tacos", emoji: "Tc" },
  { key: "thai", label: "Thai", emoji: "Th" },
  { key: "chinese", label: "Chinese", emoji: "Cn" },
  { key: "mediterranean", label: "Mediterranean", emoji: "Md" },
  { key: "bbq", label: "BBQ", emoji: "BQ" },
  { key: "seafood", label: "Seafood", emoji: "Sf" },
  { key: "breakfast", label: "Brunch", emoji: "Br" },
  { key: "healthy", label: "Healthy", emoji: "He" },
  { key: "indian", label: "Indian", emoji: "In" },
  { key: "steak", label: "Steak", emoji: "St" },
  { key: "boba", label: "Boba", emoji: "Bo" },
  { key: "sweet", label: "Dessert", emoji: "Ds" },
  { key: "coffee", label: "Coffee", emoji: "Cf" },
];

export const RESTAURANTS: Restaurant[] = [
  {
    id: "midnight-diner",
    name: "Midnight Diner",
    blurb: "Smash burgers / Loaded fries / Shakes",
    emoji: "🍔",
    photo: P.burger,
    gradient: "linear-gradient(135deg,#f7b733,#fc4a1a)",
    rating: 4.9,
    reviewsCount: 2841,
    etaMin: 18,
    distanceKm: 1.2,
    priceLevel: "$$",
    category: "American",
    tags: ["burger"],
    sections: [
      {
        title: "Burgers",
        items: [
          { id: "md1", name: "The Phantom Double", desc: "Two smashed patties, molten cheddar, house sauce, pickles", price: 12.49, emoji: "🍔", photo: P.burger2, tag: "Popular", popular: true },
          { id: "md2", name: "Classic Cheeseburger", desc: "Single patty, American cheese, lettuce, tomato", price: 9.95, emoji: "🍔", photo: P.burger },
          { id: "md3", name: "Crispy Chicken Stack", desc: "Buttermilk-fried chicken, pickles, honey heat", price: 11.25, emoji: "🍗", photo: P.chickenSandwich, popular: true },
        ],
      },
      {
        title: "Sides & shakes",
        items: [
          { id: "md4", name: "Truffle Loaded Fries", desc: "Hand-cut fries, parmesan, truffle oil, chives", price: 7.5, emoji: "🍟", photo: P.fries, popular: true },
          { id: "md5", name: "Sweet Potato Fries", desc: "Crispy, dusted with smoked paprika salt", price: 5.75, emoji: "🍠", photo: P.fries },
          { id: "md6", name: "Vanilla Malt Shake", desc: "Thick, hand-spun, real vanilla bean", price: 5.95, emoji: "🥤", photo: P.shake },
          { id: "md7", name: "Salted Caramel Shake", desc: "Burnt-sugar caramel, sea salt, whipped cream", price: 6.5, emoji: "🥤", photo: P.shake },
        ],
      },
    ],
    reviews: [
      { user: "nightowl", rating: 5, text: "Browsed at 3am for 40 minutes. Slept great. Spent nothing.", ago: "2h" },
      { user: "soft.landing", rating: 5, text: "The fries don't exist and I've never been happier.", ago: "1d" },
    ],
  },
  {
    id: "seoul-fryer",
    name: "Seoul Fryer",
    blurb: "Korean fried chicken / Wings / Tenders",
    emoji: "🍗",
    photo: P.koreanChicken,
    gradient: "linear-gradient(135deg,#ee0979,#ff6a00)",
    rating: 4.8,
    reviewsCount: 1663,
    etaMin: 26,
    distanceKm: 2.6,
    priceLevel: "$$",
    category: "Korean",
    tags: ["chicken"],
    sections: [
      {
        title: "Fried chicken",
        items: [
          { id: "sf1", name: "Gochujang Glazed Wings", desc: "Double-fried, sweet-spicy gochujang, sesame", price: 13.95, emoji: "🍗", photo: P.wings, tag: "Popular", popular: true },
          { id: "sf2", name: "Soy Garlic Half Bird", desc: "Eight pieces, glossy soy-garlic lacquer", price: 18.5, emoji: "🍗", photo: P.koreanChicken, popular: true },
          { id: "sf3", name: "Snow Cheese Tenders", desc: "Crunchy tenders, parmesan snow, ranch", price: 12.25, emoji: "🧀", photo: P.chickenSandwich },
        ],
      },
      {
        title: "Sides",
        items: [
          { id: "sf4", name: "Kimchi Fries", desc: "Fries, melted cheese, kimchi, scallion", price: 7.95, emoji: "🍟", photo: P.fries },
          { id: "sf5", name: "Crispy Spring Rolls (4)", desc: "Vegetable, sweet chili dip", price: 6.5, emoji: "🥟", photo: P.springrolls },
        ],
      },
    ],
    reviews: [
      { user: "crispy.kim", rating: 5, text: "I add the half bird every night. Cholesterol: untouched.", ago: "6h" },
      { user: "seoulmate", rating: 5, text: "The glaze looks so real I licked my screen. No regrets.", ago: "3d" },
    ],
  },
  {
    id: "el-pastor",
    name: "El Pastor",
    blurb: "Street tacos / Burritos / Nachos",
    emoji: "🌮",
    photo: P.tacos1,
    gradient: "linear-gradient(135deg,#f12711,#f5af19)",
    rating: 4.7,
    reviewsCount: 2104,
    etaMin: 20,
    distanceKm: 1.5,
    priceLevel: "$",
    category: "Mexican",
    tags: ["taco"],
    sections: [
      {
        title: "Tacos",
        items: [
          { id: "ep1", name: "Al Pastor Tacos (3)", desc: "Marinated pork, pineapple, onion, cilantro", price: 9.5, emoji: "🌮", photo: P.tacos1, tag: "Popular", popular: true },
          { id: "ep2", name: "Carnitas Tacos (3)", desc: "Slow-braised pork, salsa verde, lime", price: 9.95, emoji: "🌮", photo: P.tacos2, popular: true },
          { id: "ep3", name: "Baja Fish Tacos (3)", desc: "Crispy cod, cabbage slaw, chipotle crema", price: 11.25, emoji: "🐟", photo: P.tacos1 },
        ],
      },
      {
        title: "More",
        items: [
          { id: "ep4", name: "Carne Asada Burrito", desc: "Grilled steak, rice, beans, guac, cheese", price: 11.95, emoji: "🌯", photo: P.burrito, popular: true },
          { id: "ep5", name: "Chicken Quesadilla", desc: "Grilled chicken, three-cheese blend", price: 10.5, emoji: "🫓", photo: P.quesadilla },
          { id: "ep6", name: "Loaded Nachos", desc: "Queso, jalapenos, pico, sour cream", price: 8.75, emoji: "🧀", photo: P.nachos },
          { id: "ep7", name: "Guac & Chips", desc: "Hand-mashed avocado, warm tortilla chips", price: 5.25, emoji: "🥑", photo: P.guac },
        ],
      },
    ],
    reviews: [
      { user: "taco.tues", rating: 5, text: "Filled a cart with 9 tacos and paid in pure imagination.", ago: "4h" },
      { user: "m.flores", rating: 4, text: "The pineapple on the pastor looks unreal. Because it is.", ago: "2d" },
    ],
  },
  {
    id: "slurp-house",
    name: "Slurp House",
    blurb: "Hand-pulled ramen / Rich tonkotsu broth",
    emoji: "🍜",
    photo: P.ramen,
    gradient: "linear-gradient(135deg,#f5a623,#f76b1c)",
    rating: 4.8,
    reviewsCount: 1932,
    etaMin: 24,
    distanceKm: 2.1,
    priceLevel: "$$",
    category: "Japanese",
    tags: ["noodle"],
    sections: [
      {
        title: "Signature bowls",
        items: [
          { id: "sh1", name: "Golden Tonkotsu", desc: "18-hour pork broth, chashu, ajitama egg", price: 13.95, emoji: "🍜", photo: P.tonkotsu, tag: "Chef's pick", popular: true },
          { id: "sh2", name: "Spicy Miso Tantanmen", desc: "Sesame, chili oil, minced pork, bok choy", price: 13.5, emoji: "🌶️", photo: P.ramen2, popular: true },
          { id: "sh3", name: "Yuzu Shio Clear", desc: "Light citrus broth, chicken, bamboo shoots", price: 12.25, emoji: "🥢", photo: P.ramen },
        ],
      },
      {
        title: "Sides",
        items: [
          { id: "sh4", name: "Pork Gyoza (6)", desc: "Pan-seared, crispy skirt, ponzu", price: 6.95, emoji: "🥟", photo: P.gyoza },
          { id: "sh5", name: "Chicken Karaage", desc: "Japanese fried chicken, lemon, kewpie", price: 7.5, emoji: "🍗", photo: P.chickenSandwich },
          { id: "sh6", name: "Matcha Soft Serve", desc: "Stone-ground matcha, faintly bitter", price: 4.95, emoji: "🍦", photo: P.matcha },
        ],
      },
    ],
    reviews: [
      { user: "broth.believer", rating: 5, text: "I watch the steam loop and forget I was hungry.", ago: "5h" },
      { user: "minji", rating: 5, text: "No delivery fee because no delivery. Genius.", ago: "4d" },
    ],
  },
  {
    id: "pho-real",
    name: "Pho Real",
    blurb: "Vietnamese pho / Banh mi / Spring rolls",
    emoji: "🍜",
    photo: P.pho,
    gradient: "linear-gradient(135deg,#00b09b,#96c93d)",
    rating: 4.7,
    reviewsCount: 1188,
    etaMin: 27,
    distanceKm: 3.0,
    priceLevel: "$$",
    category: "Vietnamese",
    tags: ["noodle"],
    sections: [
      {
        title: "Pho & noodles",
        items: [
          { id: "pr1", name: "Beef Pho Tai", desc: "Rare beef, rice noodles, 12-hour bone broth", price: 12.95, emoji: "🍜", photo: P.pho, tag: "Popular", popular: true },
          { id: "pr2", name: "Chicken Pho", desc: "Poached chicken, ginger, scallion, herbs", price: 11.5, emoji: "🍜", photo: P.pho },
        ],
      },
      {
        title: "Sides & sips",
        items: [
          { id: "pr3", name: "Grilled Pork Banh Mi", desc: "Lemongrass pork, pate, pickled veg, baguette", price: 8.95, emoji: "🥖", photo: P.banhmi, popular: true },
          { id: "pr4", name: "Crispy Spring Rolls (4)", desc: "Shrimp & pork, nuoc cham dip", price: 6.5, emoji: "🥟", photo: P.springrolls },
          { id: "pr5", name: "Vietnamese Iced Coffee", desc: "Robusta, condensed milk, over ice", price: 4.75, emoji: "🧊", photo: P.coldbrew },
        ],
      },
    ],
    reviews: [
      { user: "broth.again", rating: 5, text: "The steam animation is so good I needed a nap, not a meal.", ago: "9h" },
      { user: "t.nguyen", rating: 4, text: "Banh mi looked crispier than my real lunch. Sad but true.", ago: "5d" },
    ],
  },
  {
    id: "drift-sushi",
    name: "Drift Sushi",
    blurb: "Omakase sets / Nigiri / Signature rolls",
    emoji: "🍣",
    photo: P.sushi,
    gradient: "linear-gradient(135deg,#11998e,#38ef7d)",
    rating: 4.9,
    reviewsCount: 1577,
    etaMin: 29,
    distanceKm: 3.4,
    priceLevel: "$$$",
    category: "Sushi",
    tags: ["sushi"],
    sections: [
      {
        title: "Sets & rolls",
        items: [
          { id: "ds1", name: "Drifter's Omakase (12pc)", desc: "Chef-selected nigiri, daily catch", price: 27.5, emoji: "🍣", photo: P.nigiri, tag: "Premium", popular: true },
          { id: "ds2", name: "Salmon Trio", desc: "Nigiri, aburi, and ikura - pink everywhere", price: 15.95, emoji: "🍥", photo: P.salmon, popular: true },
          { id: "ds3", name: "Dragon Roll", desc: "Eel, avocado, cucumber, unagi glaze", price: 14.5, emoji: "🐉", photo: P.dragonroll },
          { id: "ds4", name: "Spicy Tuna Roll", desc: "Tuna, chili mayo, scallion, tempura crunch", price: 11.25, emoji: "🍣", photo: P.sushi },
        ],
      },
      {
        title: "Sides & drinks",
        items: [
          { id: "ds5", name: "Pork Gyoza (6)", desc: "Pan-seared, crispy skirt, ponzu", price: 7.95, emoji: "🥟", photo: P.gyoza },
          { id: "ds6", name: "Cold Junmai Sake", desc: "Served frosty, 180ml carafe", price: 8.95, emoji: "🍶", photo: P.sake },
          { id: "ds7", name: "Yuzu Sparkling", desc: "Bright, fizzy, zero alcohol", price: 4.25, emoji: "🥂", photo: P.sparkling },
        ],
      },
    ],
    reviews: [
      { user: "wallet.zen", rating: 5, text: "Ordered the $27 omakase nightly. Balance: untouched.", ago: "8h" },
      { user: "quietquit", rating: 5, text: "All the luxury, none of the bill. This is the future.", ago: "6d" },
    ],
  },
  {
    id: "dough-theory",
    name: "Dough Theory",
    blurb: "Sourdough pizza / Wood-fired / Shareable",
    emoji: "🍕",
    photo: P.pizza,
    gradient: "linear-gradient(135deg,#ee0979,#ff6a00)",
    rating: 4.7,
    reviewsCount: 1204,
    etaMin: 22,
    distanceKm: 1.8,
    priceLevel: "$$",
    category: "Italian",
    tags: ["pizza"],
    sections: [
      {
        title: "From the oven",
        items: [
          { id: "dt1", name: "Hot Honey Pepperoni", desc: "Cup-and-char pepperoni, chili honey drizzle", price: 16.95, emoji: "🍕", photo: P.pepperoni, tag: "Popular", popular: true },
          { id: "dt2", name: "Burrata Margherita", desc: "San Marzano, torn basil, creamy burrata", price: 15.5, emoji: "🧀", photo: P.margherita, popular: true },
          { id: "dt3", name: "Wild Mushroom & Truffle", desc: "Fontina, thyme, truffle cream", price: 17.25, emoji: "🍄", photo: P.mushroomPizza },
          { id: "dt4", name: "Classic Cheese", desc: "Mozzarella, San Marzano, olive oil", price: 13.95, emoji: "🧀", photo: P.pizza },
        ],
      },
      {
        title: "Sides & dessert",
        items: [
          { id: "dt5", name: "Garlic Knots (5)", desc: "Buttery, herby, parmesan dust", price: 5.95, emoji: "🥖", photo: P.garlicBread },
          { id: "dt6", name: "Tiramisu Cup", desc: "Espresso-soaked, mascarpone, cocoa", price: 6.5, emoji: "🍰", photo: P.tiramisu },
        ],
      },
    ],
    reviews: [
      { user: "carb.dreamer", rating: 5, text: "Built the perfect order, closed the tab, felt complete.", ago: "3h" },
      { user: "lee.w", rating: 4, text: "The dough-rising animation is chef's kiss.", ago: "5d" },
    ],
  },
  {
    id: "green-bowl",
    name: "Green Bowl",
    blurb: "Poke / Grain bowls / Cold-pressed",
    emoji: "🥗",
    photo: P.poke,
    gradient: "linear-gradient(135deg,#00b09b,#96c93d)",
    rating: 4.6,
    reviewsCount: 942,
    etaMin: 19,
    distanceKm: 1.1,
    priceLevel: "$$",
    category: "Healthy",
    tags: ["healthy"],
    sections: [
      {
        title: "Bowls",
        items: [
          { id: "gb1", name: "Ahi Poke Bowl", desc: "Tuna, sushi rice, edamame, avocado, sesame", price: 14.25, emoji: "🥗", photo: P.poke, tag: "Popular", popular: true },
          { id: "gb2", name: "Harvest Grain Bowl", desc: "Quinoa, roasted veg, chickpeas, tahini", price: 11.95, emoji: "🥙", photo: P.grainBowl, popular: true },
          { id: "gb3", name: "Caesar Crunch Salad", desc: "Romaine, parmesan, croutons, lemon", price: 9.95, emoji: "🥗", photo: P.salad },
        ],
      },
      {
        title: "Lighter bites",
        items: [
          { id: "gb4", name: "Avocado Toast", desc: "Sourdough, smashed avo, chili, radish", price: 8.5, emoji: "🥑", photo: P.avoToast },
          { id: "gb5", name: "Green Glow Smoothie", desc: "Spinach, mango, banana, coconut water", price: 6.75, emoji: "🥤", photo: P.smoothie },
        ],
      },
    ],
    reviews: [
      { user: "clean.eats", rating: 5, text: "Zero calories consumed, infinite calories admired.", ago: "7h" },
      { user: "r.patel", rating: 4, text: "Built a $40 healthy order and felt virtuous for free.", ago: "3d" },
    ],
  },
  {
    id: "curry-club",
    name: "Curry Club",
    blurb: "North Indian / Biryani / Tandoor",
    emoji: "🍛",
    photo: P.butterChicken,
    gradient: "linear-gradient(135deg,#f12711,#f5af19)",
    rating: 4.8,
    reviewsCount: 1421,
    etaMin: 31,
    distanceKm: 3.6,
    priceLevel: "$$",
    category: "Indian",
    tags: ["indian"],
    sections: [
      {
        title: "Curries & rice",
        items: [
          { id: "cc1", name: "Butter Chicken", desc: "Tandoori chicken, tomato-cream gravy", price: 13.95, emoji: "🍛", photo: P.butterChicken, tag: "Popular", popular: true },
          { id: "cc2", name: "Chicken Tikka Masala", desc: "Charred chicken, spiced onion-tomato masala", price: 13.5, emoji: "🍛", photo: P.tikka, popular: true },
          { id: "cc3", name: "Lamb Biryani", desc: "Basmati, slow-cooked lamb, fried onion, raita", price: 15.25, emoji: "🍚", photo: P.biryani, popular: true },
        ],
      },
      {
        title: "Breads & sides",
        items: [
          { id: "cc4", name: "Garlic Naan (2)", desc: "Tandoor-blistered, brushed with garlic butter", price: 4.25, emoji: "🫓", photo: P.naan },
          { id: "cc5", name: "Veg Samosa (3)", desc: "Crispy pastry, spiced potato & pea", price: 5.95, emoji: "🥟", photo: P.springrolls },
          { id: "cc6", name: "Mango Lassi", desc: "Yogurt, alphonso mango, cardamom", price: 4.5, emoji: "🥭", photo: P.smoothie },
        ],
      },
    ],
    reviews: [
      { user: "spice.route", rating: 5, text: "The butter chicken glistens. I have never been so full of nothing.", ago: "10h" },
      { user: "a.sharma", rating: 5, text: "Naan basket for two, party for none. Loved it.", ago: "4d" },
    ],
  },
  {
    id: "sugar-hour",
    name: "Sugar Hour",
    blurb: "Cakes / Cookies / Ice cream",
    emoji: "🍰",
    photo: P.cake,
    gradient: "linear-gradient(135deg,#ff5f6d,#ffc371)",
    rating: 4.9,
    reviewsCount: 2670,
    etaMin: 17,
    distanceKm: 0.9,
    priceLevel: "$",
    category: "Desserts",
    tags: ["sweet"],
    sections: [
      {
        title: "Cakes & bakes",
        items: [
          { id: "su1", name: "New York Cheesecake", desc: "Dense, vanilla, graham crust, berry coulis", price: 7.25, emoji: "🍰", photo: P.cheesecake, tag: "Popular", popular: true },
          { id: "su2", name: "Molten Chocolate Cake", desc: "Warm, oozing center, cocoa dust", price: 7.95, emoji: "🍫", photo: P.cake, popular: true },
          { id: "su3", name: "Brown Butter Cookies (3)", desc: "Crisp edge, gooey middle, sea salt", price: 5.95, emoji: "🍪", photo: P.cookie },
        ],
      },
      {
        title: "Sweet & cold",
        items: [
          { id: "su4", name: "Glazed Donut Box (4)", desc: "Classic glaze, still-warm dough", price: 8.5, emoji: "🍩", photo: P.donut },
          { id: "su5", name: "Vanilla Bean Ice Cream", desc: "Two scoops, real bean speckle", price: 4.75, emoji: "🍨", photo: P.icecream },
          { id: "su6", name: "Belgian Waffle", desc: "Pearl sugar, berries, maple", price: 8.25, emoji: "🧇", photo: P.waffle },
        ],
      },
    ],
    reviews: [
      { user: "sweet.tooth", rating: 5, text: "Ordered cake at midnight, ate nothing, woke up thin and happy.", ago: "1h" },
      { user: "b.cho", rating: 5, text: "The molten cake animation should be illegal. So good.", ago: "2d" },
    ],
  },
  {
    id: "bean-theory",
    name: "Bean Theory",
    blurb: "Specialty coffee / Pastries / Brunch",
    emoji: "☕",
    photo: P.cappuccino,
    gradient: "linear-gradient(135deg,#c79081,#dfa579)",
    rating: 4.8,
    reviewsCount: 1985,
    etaMin: 15,
    distanceKm: 0.7,
    priceLevel: "$",
    category: "Coffee & Bakery",
    tags: ["coffee"],
    sections: [
      {
        title: "Coffee",
        items: [
          { id: "bt1", name: "Cappuccino", desc: "Double shot, velvet microfoam, cocoa", price: 4.25, emoji: "☕", photo: P.cappuccino, tag: "Popular", popular: true },
          { id: "bt2", name: "Cold Brew", desc: "18-hour steep, smooth, low acid", price: 4.75, emoji: "🧊", photo: P.coldbrew, popular: true },
          { id: "bt3", name: "Cortado", desc: "Equal parts espresso and warm milk", price: 3.95, emoji: "☕", photo: P.espresso },
          { id: "bt4", name: "Iced Matcha Latte", desc: "Ceremonial matcha, oat milk", price: 5.25, emoji: "🍵", photo: P.matcha },
        ],
      },
      {
        title: "Bakery",
        items: [
          { id: "bt5", name: "Butter Croissant", desc: "72-hour laminated, shatteringly flaky", price: 3.49, emoji: "🥐", photo: P.croissant },
          { id: "bt6", name: "Buttermilk Pancake Stack", desc: "Three stack, maple, whipped butter", price: 9.5, emoji: "🥞", photo: P.pancakes },
        ],
      },
    ],
    reviews: [
      { user: "first.sip", rating: 5, text: "I 'order' a cortado every morning. Cheapest habit I own.", ago: "3h" },
      { user: "k.lee", rating: 5, text: "The latte art is realer than my barista's. Wild.", ago: "1d" },
    ],
  },
  {
    id: "bangkok-heat",
    name: "Bangkok Heat",
    blurb: "Pad thai / Curries / Thai street food",
    emoji: "🍤",
    photo: P.padthai,
    gradient: "linear-gradient(135deg,#11998e,#38ef7d)",
    rating: 4.8,
    reviewsCount: 1488,
    etaMin: 28,
    distanceKm: 2.9,
    priceLevel: "$$",
    category: "Thai",
    tags: ["thai"],
    sections: [
      {
        title: "Wok & noodles",
        items: [
          { id: "bh1", name: "Pad Thai", desc: "Rice noodles, tamarind, peanuts, lime, shrimp", price: 11.95, emoji: "🍤", photo: P.padthai, tag: "Popular", popular: true },
          { id: "bh2", name: "Green Curry Chicken", desc: "Coconut milk, thai basil, bamboo, jasmine rice", price: 13.25, emoji: "🍛", photo: P.greenCurry, popular: true },
          { id: "bh3", name: "Thai Basil Stir-Fry", desc: "Minced chicken, holy basil, chili, fried egg", price: 12.5, emoji: "🌶️", photo: P.thaiBasil },
        ],
      },
      {
        title: "Sides & sips",
        items: [
          { id: "bh4", name: "Crispy Spring Rolls (4)", desc: "Glass noodle, vegetable, sweet chili", price: 6.25, emoji: "🥟", photo: P.springrolls },
          { id: "bh5", name: "Thai Iced Tea", desc: "Black tea, condensed milk, over ice", price: 4.5, emoji: "🧋", photo: P.milkTea },
        ],
      },
    ],
    reviews: [
      { user: "spice.lvl.5", rating: 5, text: "Set it to Thai hot, felt the burn, ate nothing. Iconic.", ago: "4h" },
      { user: "p.somchai", rating: 5, text: "The pad thai photo alone fed my soul.", ago: "2d" },
    ],
  },
  {
    id: "golden-wok",
    name: "Golden Wok",
    blurb: "Dumplings / Fried rice / Chinese classics",
    emoji: "🥡",
    photo: P.dumplings,
    gradient: "linear-gradient(135deg,#f12711,#f5af19)",
    rating: 4.7,
    reviewsCount: 2012,
    etaMin: 25,
    distanceKm: 2.3,
    priceLevel: "$$",
    category: "Chinese",
    tags: ["chinese"],
    sections: [
      {
        title: "Most ordered",
        items: [
          { id: "gw1", name: "Pan-Fried Pork Dumplings (8)", desc: "Crispy bottoms, chili-soy dip", price: 8.95, emoji: "🥟", photo: P.dumplings, tag: "Popular", popular: true },
          { id: "gw2", name: "Yangzhou Fried Rice", desc: "Shrimp, char siu, egg, scallion", price: 11.5, emoji: "🍚", photo: P.friedRice, popular: true },
          { id: "gw3", name: "Chicken Chow Mein", desc: "Stir-fried egg noodles, crunchy veg", price: 12.25, emoji: "🍜", photo: P.chowMein },
        ],
      },
      {
        title: "Soups & sides",
        items: [
          { id: "gw4", name: "Wonton Soup", desc: "Pork wontons, clear broth, bok choy", price: 7.5, emoji: "🍲", photo: P.wonton },
          { id: "gw5", name: "Veg Spring Rolls (4)", desc: "Crispy, sweet chili dip", price: 5.95, emoji: "🥟", photo: P.springrolls },
        ],
      },
    ],
    reviews: [
      { user: "dumpling.dan", rating: 5, text: "Added 40 dumplings to the cart. Wallet survived. Genius.", ago: "6h" },
      { user: "mei.l", rating: 4, text: "Fried rice looked steamy enough to skip dinner.", ago: "3d" },
    ],
  },
  {
    id: "olive-and-pita",
    name: "Olive & Pita",
    blurb: "Shawarma / Falafel / Mezze",
    emoji: "🥙",
    photo: P.shawarma,
    gradient: "linear-gradient(135deg,#00b09b,#96c93d)",
    rating: 4.8,
    reviewsCount: 1344,
    etaMin: 23,
    distanceKm: 1.9,
    priceLevel: "$$",
    category: "Mediterranean",
    tags: ["mediterranean"],
    sections: [
      {
        title: "Wraps & plates",
        items: [
          { id: "op1", name: "Chicken Shawarma Wrap", desc: "Garlic toum, pickles, fries, saj bread", price: 10.95, emoji: "🥙", photo: P.shawarma, tag: "Popular", popular: true },
          { id: "op2", name: "Falafel Plate", desc: "Six falafel, hummus, salad, tahini", price: 11.5, emoji: "🧆", photo: P.falafel, popular: true },
          { id: "op3", name: "Greek Salad", desc: "Tomato, cucumber, feta, olives, oregano", price: 9.25, emoji: "🥗", photo: P.greekSalad },
        ],
      },
      {
        title: "Mezze",
        items: [
          { id: "op4", name: "Hummus & Warm Pita", desc: "Olive oil, paprika, chickpea, lemon", price: 6.95, emoji: "🫓", photo: P.hummus },
        ],
      },
    ],
    reviews: [
      { user: "mezze.maven", rating: 5, text: "Built a full mezze spread for zero dollars. Mediterranean diet, perfected.", ago: "8h" },
      { user: "y.haddad", rating: 5, text: "That toum garlic glisten? Unreal. Literally.", ago: "4d" },
    ],
  },
  {
    id: "smoke-stack",
    name: "Smoke Stack BBQ",
    blurb: "Brisket / Ribs / Low and slow",
    emoji: "🍖",
    photo: P.brisket,
    gradient: "linear-gradient(135deg,#f7b733,#fc4a1a)",
    rating: 4.7,
    reviewsCount: 1779,
    etaMin: 30,
    distanceKm: 3.8,
    priceLevel: "$$$",
    category: "BBQ",
    tags: ["bbq"],
    sections: [
      {
        title: "From the smoker",
        items: [
          { id: "ss1", name: "Sliced Brisket Plate", desc: "12-hour smoked, two sides, pickles", price: 16.95, emoji: "🥩", photo: P.brisket, tag: "Popular", popular: true },
          { id: "ss2", name: "Baby Back Ribs", desc: "Full rack, dry rub, glossy glaze", price: 18.5, emoji: "🍖", photo: P.ribs, popular: true },
          { id: "ss3", name: "Pulled Pork Sandwich", desc: "Brioche bun, slaw, house sauce", price: 11.95, emoji: "🥪", photo: P.pulledPork },
        ],
      },
      {
        title: "Sides",
        items: [
          { id: "ss4", name: "Loaded Pit Fries", desc: "Burnt ends, cheese, scallion", price: 7.5, emoji: "🍟", photo: P.fries },
        ],
      },
    ],
    reviews: [
      { user: "low.n.slow", rating: 5, text: "Smelled the screen. Ordered a whole rack. Paid in dreams.", ago: "5h" },
      { user: "tex.b", rating: 4, text: "The bark on that brisket photo is criminal.", ago: "6d" },
    ],
  },
  {
    id: "catch-and-co",
    name: "Catch & Co",
    blurb: "Fish & chips / Shrimp / Fresh catch",
    emoji: "🦐",
    photo: P.fishChips,
    gradient: "linear-gradient(135deg,#11998e,#38ef7d)",
    rating: 4.8,
    reviewsCount: 1206,
    etaMin: 27,
    distanceKm: 3.1,
    priceLevel: "$$",
    category: "Seafood",
    tags: ["seafood"],
    sections: [
      {
        title: "Fried & fresh",
        items: [
          { id: "cc1", name: "Beer-Battered Fish & Chips", desc: "Cod, thick chips, tartar, lemon", price: 13.95, emoji: "🐟", photo: P.fishChips, tag: "Popular", popular: true },
          { id: "cc2", name: "Garlic Butter Shrimp", desc: "Seared, herbs, crusty bread", price: 15.5, emoji: "🦐", photo: P.shrimp, popular: true },
          { id: "cc3", name: "Crispy Calamari", desc: "Lightly fried, aioli, lemon", price: 9.95, emoji: "🦑", photo: P.calamari },
        ],
      },
      {
        title: "Baskets",
        items: [
          { id: "cc4", name: "Fried Shrimp Basket", desc: "Cornmeal crust, fries, cocktail sauce", price: 12.25, emoji: "🍤", photo: P.friedShrimp },
          { id: "cc5", name: "Seafood Platter", desc: "Shrimp, calamari, fish, slaw - the works", price: 24.5, emoji: "🦞", photo: P.seafoodPlatter },
        ],
      },
    ],
    reviews: [
      { user: "deep.blue", rating: 5, text: "The platter is $24 of pure imagination. Worth every fake cent.", ago: "7h" },
      { user: "s.marin", rating: 5, text: "Calamari so crisp I heard it. I did not.", ago: "5d" },
    ],
  },
  {
    id: "sunrise-brunch",
    name: "Sunrise Brunch",
    blurb: "Eggs / Pancakes / All-day brunch",
    emoji: "🍳",
    photo: P.eggsBenedict,
    gradient: "linear-gradient(135deg,#ff5f6d,#ffc371)",
    rating: 4.8,
    reviewsCount: 1922,
    etaMin: 19,
    distanceKm: 1.0,
    priceLevel: "$$",
    category: "Brunch",
    tags: ["breakfast"],
    sections: [
      {
        title: "Brunch plates",
        items: [
          { id: "sb1", name: "Eggs Benedict", desc: "Poached eggs, ham, hollandaise, muffin", price: 12.95, emoji: "🍳", photo: P.eggsBenedict, tag: "Popular", popular: true },
          { id: "sb2", name: "Buttermilk Pancakes", desc: "Tall stack, maple, whipped butter", price: 9.95, emoji: "🥞", photo: P.pancakes, popular: true },
          { id: "sb3", name: "Belgian Waffle", desc: "Pearl sugar, berries, cream", price: 9.5, emoji: "🧇", photo: P.waffle },
        ],
      },
      {
        title: "Lighter & sips",
        items: [
          { id: "sb4", name: "Avocado Toast", desc: "Sourdough, smashed avo, chili, egg", price: 8.95, emoji: "🥑", photo: P.avoToast },
          { id: "sb5", name: "Cold Brew", desc: "Smooth, low acid, over ice", price: 4.75, emoji: "🧊", photo: P.coldbrew },
        ],
      },
    ],
    reviews: [
      { user: "brunch.club", rating: 5, text: "Benedict at 2pm, no judgment, no bill. Perfect brunch.", ago: "3h" },
      { user: "a.rivera", rating: 5, text: "That hollandaise drip should be illegal.", ago: "2d" },
    ],
  },
  {
    id: "prime-cut",
    name: "Prime Cut",
    blurb: "Steakhouse / Grills / Big plates",
    emoji: "🥩",
    photo: P.steak,
    gradient: "linear-gradient(135deg,#ee0979,#ff6a00)",
    rating: 4.9,
    reviewsCount: 1357,
    etaMin: 33,
    distanceKm: 4.2,
    priceLevel: "$$$",
    category: "Steakhouse",
    tags: ["steak"],
    sections: [
      {
        title: "From the grill",
        items: [
          { id: "pc1", name: "Ribeye Steak", desc: "12oz, herb butter, your choice of side", price: 27.95, emoji: "🥩", photo: P.steak, tag: "Premium", popular: true },
          { id: "pc2", name: "Steak Frites", desc: "Sirloin, peppercorn sauce, fries", price: 19.5, emoji: "🍟", photo: P.steak, popular: true },
        ],
      },
      {
        title: "Sides",
        items: [
          { id: "pc3", name: "Garlic Bread", desc: "Buttery, herby, parmesan", price: 5.95, emoji: "🥖", photo: P.garlicBread },
          { id: "pc4", name: "Loaded Fries", desc: "Cheese, scallion, peppercorn drizzle", price: 7.25, emoji: "🍟", photo: P.fries },
        ],
      },
    ],
    reviews: [
      { user: "med.rare", rating: 5, text: "Ordered the ribeye nightly. My steak budget: still $0.", ago: "9h" },
      { user: "g.ferro", rating: 5, text: "The sear on that ribeye photo? Restaurant quality. Literally.", ago: "1d" },
    ],
  },
  {
    id: "boba-lab",
    name: "Boba Lab",
    blurb: "Milk tea / Brown sugar boba / Fruit tea",
    emoji: "🧋",
    photo: P.bubbleTea,
    gradient: "linear-gradient(135deg,#c79081,#dfa579)",
    rating: 4.9,
    reviewsCount: 2455,
    etaMin: 16,
    distanceKm: 0.8,
    priceLevel: "$",
    category: "Boba",
    tags: ["boba"],
    sections: [
      {
        title: "Signature teas",
        items: [
          { id: "bl1", name: "Brown Sugar Boba", desc: "Fresh milk, caramelized tapioca, tiger stripes", price: 5.95, emoji: "🧋", photo: P.bubbleTea, tag: "Popular", popular: true },
          { id: "bl2", name: "Classic Milk Tea", desc: "Black tea, creamer, chewy boba", price: 5.25, emoji: "🧋", photo: P.milkTea, popular: true },
          { id: "bl3", name: "Taro Milk Tea", desc: "Stone-ground taro, milk, boba", price: 5.75, emoji: "🟣", photo: P.bubbleTea },
        ],
      },
      {
        title: "More",
        items: [
          { id: "bl4", name: "Iced Matcha Latte", desc: "Ceremonial matcha, oat milk", price: 5.5, emoji: "🍵", photo: P.matcha },
        ],
      },
    ],
    reviews: [
      { user: "boba.brain", rating: 5, text: "Customized the sweetness to 0%, calories to 0, joy to 100%.", ago: "1h" },
      { user: "w.tan", rating: 5, text: "Those tiger stripes are hypnotic. Stayed 15 minutes.", ago: "2d" },
    ],
  },
];
